### ISSUE TITLE
Změna API URL

### ISSUE THREAD

**Issue by radimvaculik** [contributte/fio#13]
Vážený kliente,

rádi bychom Vás informovali, že v rámci dalšího zvýšení bezpečnosti našich služeb dochází k přesunu domény Fio API Bankovnictví ze stávající https://www.fio.cz/ib_api/ na samostatnou URL https://fioapi.fio.cz/.

Nově je třeba směřovat pokyny zasílané z API Bankovnictví na tuto novou URL. Abychom Vám poskytli dostatek času se této změně přizpůsobit, budou po přechodné období 6 měsíců platné obě výše uvedené adresy.

V případě dotazů nás prosím kontaktujte prostřednictvím Fio servisu ve svém internetovém nebo mobilním bankovnictví.

![image](https://github.com/contributte/fio/assets/461164/2f06861d-19b6-4490-9e5b-cd359a9197ba)

![image](https://github.com/contributte/fio/assets/461164/34fd182e-247d-49f7-bbc4-42098879004d)

**Comment by f3l1x** [comment]
https://github.com/contributte/fio/releases/tag/v0.3.0
